"""empty message

Revision ID: 687de88f03f8
Revises: 62ed7693aac8
Create Date: 2016-05-09 18:25:19.868452

"""

# revision identifiers, used by Alembic.
revision = '687de88f03f8'
down_revision = '62ed7693aac8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('deletedAt', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('editedAt', sa.DateTime(), nullable=True))
    op.drop_column('tag', 'deleted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tag', 'editedAt')
    op.drop_column('tag', 'deletedAt')
    op.drop_column('tag', 'createdAt')
    ### end Alembic commands ###
